/* eslint-disable */
// AUTO-GENERATED by `rndl typegen`. Do not edit by hand.
// Regenerate this file instead of editing it.
import { buildRouteUrl, type Route } from '@deeplink-devtools/core';
import { useLocalSearchParams } from 'expo-router';

/** Params accepted by {@link buildDeepLink}, keyed by route. All values are strings (they go into the URL). */
export interface DeepLinkRoutes {
  "/promo": Record<string, never>;
  "/home": Record<string, never>;
  "/settings": Record<string, never>;
  "/settings/notifications": Record<string, never>;
  "/[...not-found]": { "not-found"?: string };
  "/about": Record<string, never>;
  "/contact": Record<string, never>;
  "/docs/[page]": { page: string };
  "/": Record<string, never>;
  "/posts/[...slug]": { slug: string };
  "/users/[id]": { id: string };
  "/users/[id]/posts": { id: string };
}

/** Params {@link useTypedParams} returns, keyed by route, as the router hands them to the screen. */
export interface DeepLinkParams {
  "/promo": Record<string, never>;
  "/home": Record<string, never>;
  "/settings": Record<string, never>;
  "/settings/notifications": Record<string, never>;
  "/[...not-found]": { "not-found"?: string[] };
  "/about": Record<string, never>;
  "/contact": Record<string, never>;
  "/docs/[page]": { page: string };
  "/": Record<string, never>;
  "/posts/[...slug]": { slug: string[] };
  "/users/[id]": { id: string };
  "/users/[id]/posts": { id: string };
}

/** The scheme/prefix baked in at generation time; pass a prefix to {@link buildDeepLink} to override it. */
const DEFAULT_PREFIX = "exampleexporouter://";

const ROUTES: Record<keyof DeepLinkRoutes, Route> = {
  "/promo": {"name":"(marketing,shop)/promo","pattern":"/promo","params":[],"exact":true},
  "/home": {"name":"(tabs)/home","pattern":"/home","params":[],"exact":true},
  "/settings": {"name":"(tabs)/settings/index","pattern":"/settings","params":[],"exact":true},
  "/settings/notifications": {"name":"(tabs)/settings/notifications","pattern":"/settings/notifications","params":[],"exact":true},
  "/[...not-found]": {"name":"+not-found","pattern":"/*not-found","params":[{"name":"not-found","kind":"catch-all","optional":true,"tsType":"string[]"}],"exact":false},
  "/about": {"name":"about","pattern":"/about","params":[],"exact":true},
  "/contact": {"name":"contact","pattern":"/contact","params":[],"exact":true},
  "/docs/[page]": {"name":"docs/[page]","pattern":"/docs/:page","params":[{"name":"page","kind":"path","optional":false,"tsType":"string"}],"exact":true},
  "/": {"name":"index","pattern":"/","params":[],"exact":true},
  "/posts/[...slug]": {"name":"posts/[...slug]","pattern":"/posts/*slug","params":[{"name":"slug","kind":"catch-all","optional":false,"tsType":"string[]"}],"exact":false},
  "/users/[id]": {"name":"users/[id]/index","pattern":"/users/:id","params":[{"name":"id","kind":"path","optional":false,"tsType":"string"}],"exact":true},
  "/users/[id]/posts": {"name":"users/[id]/posts","pattern":"/users/:id/posts","params":[{"name":"id","kind":"path","optional":false,"tsType":"string"}],"exact":true},
};

/**
 * Build a deep-link URL for a known route. The route key and its params are
 * checked at compile time, so a wrong route or a missing/mistyped param fails
 * `tsc`. Throws if a required param is not supplied at runtime.
 */
export function buildDeepLink<R extends keyof DeepLinkRoutes>(
  route: R,
  params: DeepLinkRoutes[R],
  prefix: string = DEFAULT_PREFIX,
): string {
  const result = buildRouteUrl(ROUTES[route], params as unknown as Record<string, string>, prefix);
  if (result.url === undefined) {
    throw new Error(
      `buildDeepLink: cannot build "${String(route)}" without params: ${result.missing.join(', ')}`,
    );
  }
  return result.url;
}

/**
 * Read the current screen's deep-link params, typed for the given route. The
 * route key selects the param shape; the returned values are what the router
 * provides (strings, string arrays for catch-all, or `unknown` for a React
 * Navigation custom `parse`).
 */
export function useTypedParams<R extends keyof DeepLinkParams>(): DeepLinkParams[R] {
  return useLocalSearchParams() as unknown as DeepLinkParams[R];
}
