/* eslint-disable */
// AUTO-GENERATED by `rndl typegen`. Do not edit by hand.
// Regenerate this file instead of editing it.
import { buildRouteUrl, type Route } from '@deeplink-devtools/core';
import { useRoute } from '@react-navigation/native';

/** Params accepted by {@link buildDeepLink}, keyed by route. All values are strings (they go into the URL). */
export interface DeepLinkRoutes {
  "/": Record<string, never>;
  "/feed": Record<string, never>;
  "/feed/article/:slug/:commentId?": { slug: string; commentId?: string };
  "/search": Record<string, never>;
  "/user/:id": { id: string };
  "/u/:id": { id: string };
  "/promo/:code(SUMMER|WINTER)": { code: string };
  "/settings/notifications": Record<string, never>;
  "/*": Record<string, never>;
}

/** Params {@link useTypedParams} returns, keyed by route, as the router hands them to the screen. */
export interface DeepLinkParams {
  "/": Record<string, never>;
  "/feed": Record<string, never>;
  "/feed/article/:slug/:commentId?": { slug: string; commentId?: unknown };
  "/search": Record<string, never>;
  "/user/:id": { id: unknown };
  "/u/:id": { id: unknown };
  "/promo/:code(SUMMER|WINTER)": { code: string };
  "/settings/notifications": Record<string, never>;
  "/*": Record<string, never>;
}

/** The scheme/prefix baked in at generation time; pass a prefix to {@link buildDeepLink} to override it. */
const DEFAULT_PREFIX = "examplereactnavigation://";

const ROUTES: Record<keyof DeepLinkRoutes, Route> = {
  "/": {"name":"HomeTabs","pattern":"/","params":[],"exact":true},
  "/feed": {"name":"HomeTabs/Feed","pattern":"/feed","params":[],"exact":true},
  "/feed/article/:slug/:commentId?": {"name":"HomeTabs/Feed/Article","pattern":"/feed/article/:slug/:commentId?","params":[{"name":"slug","kind":"path","optional":false,"tsType":"string"},{"name":"commentId","kind":"path","optional":true,"tsType":"unknown (custom parse)"}],"exact":true},
  "/search": {"name":"HomeTabs/Feed/Search","pattern":"/search","params":[],"exact":true},
  "/user/:id": {"name":"HomeTabs/Profile","pattern":"/user/:id","params":[{"name":"id","kind":"path","optional":false,"tsType":"unknown (custom parse)"}],"exact":true},
  "/u/:id": {"name":"HomeTabs/Profile","pattern":"/u/:id","params":[{"name":"id","kind":"path","optional":false,"tsType":"unknown (custom parse)"}],"exact":true},
  "/promo/:code(SUMMER|WINTER)": {"name":"Promo","pattern":"/promo/:code(SUMMER|WINTER)","params":[{"name":"code","kind":"path","optional":false,"tsType":"string"}],"exact":true},
  "/settings/notifications": {"name":"Settings/Notifications","pattern":"/settings/notifications","params":[],"exact":true},
  "/*": {"name":"NotFound","pattern":"/*","params":[],"exact":false},
};

/**
 * Build a deep-link URL for a known route. The route key and its params are
 * checked at compile time, so a wrong route or a missing/mistyped param fails
 * `tsc`. Throws if a required param is not supplied at runtime.
 */
export function buildDeepLink<R extends keyof DeepLinkRoutes>(
  route: R,
  params: DeepLinkRoutes[R],
  prefix: string = DEFAULT_PREFIX,
): string {
  const result = buildRouteUrl(ROUTES[route], params as unknown as Record<string, string>, prefix);
  if (result.url === undefined) {
    throw new Error(
      `buildDeepLink: cannot build "${String(route)}" without params: ${result.missing.join(', ')}`,
    );
  }
  return result.url;
}

/**
 * Read the current screen's deep-link params, typed for the given route. The
 * route key selects the param shape; the returned values are what the router
 * provides (strings, string arrays for catch-all, or `unknown` for a React
 * Navigation custom `parse`).
 */
export function useTypedParams<R extends keyof DeepLinkParams>(): DeepLinkParams[R] {
  return (useRoute().params ?? {}) as unknown as DeepLinkParams[R];
}
